<?php
$name = '';
$email = '';
$password = '';

$user = isset($viewParams['user']) ? $viewParams['user'] : null;

if ($user) {
    echo '<h2>Edit user' . $user->id . '</h2>';
    $name       = $user->name;
    $email      = $user->email;
    $password   = $user->password;
}
?>

<form action="<?= $user ? "/users/{$user->id}/edit" : '/users/add' ?>" method="post">
    <table border="3" cellpadding="5">
        <tbody>
        <tr>
            <td>Name</td>
            <td>Password</td>
            <td>Email</td>
            <td>Actions</td>
        </tr>
        <tr>
            <td><input type="text" name="Name" value="<?= $name ?>"></td>
            <td><input type="text" name="Email" value="<?= $email ?>"></td>
            <td><input type="text" name="Password" value="<?= $password ?>"></td>
            <td><button>Save</button></td>
        </tr>
        </tbody>
    </table>
</form>
