
<?
$name = '';
$email = '';
$password = '';
if ((bool)preg_match('/\/users\/add\/?$/', $uri)) {
    $link = '/users/added';
} else
    if ((bool)preg_match('/\/users\/(\d+)\/edit\/?$/', $uri)) {
        echo '<h2>Edit user' . $user->id . '</h2>';
        $name       = $user->name;
        $email      = $user->email;
        $password   = $user->password;
        $link = '/users/' . $user->id . '/edited';
    }
?>

<table border="3" cellpadding="5">
    <tr>
        <td>Name</td>
        <td>Password</td>
        <td>Email</td>
    </tr>
    <tr>
        <form action="<?= $link ?>" method="post">
            <td><input type="text" name="Name" value="<?= $name ?>"></td>
            <td><input type="text" name="Email" value="<?= $email ?>"></td>
            <td><input type="text" name="Password" value="<?= $password ?>"></td>
    </tr>
</table>
    <button>Save</button>
</form>