<?php
    $users = $viewParams['users'];

?>

<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }
</style>

<? if (isset($viewParams['deletedUserID']) && $viewParams['deletedUserID']): ?>
    <h2>User with ID <?= $viewParams['deletedUserID'] ?> has been deleted!</h2>
<? endif ?>

<table border="3" cellpadding="5">
<? foreach ($users as $user): ?>
    <tr>
        <td><?= $user->id ?></td>
        <td><?= $user->name ?></td>
        <td><?= $user->password ?></td>
        <td>
            <a href="/users/<?=$user->id?>/edit">
                <button>Edit</button>
            </a>
        <td>
            <a href="/users/<?=$user->id?>/delete">Delete</a>
        </td>
    </tr>
<? endforeach ?>
</table>
<br>
<a href="/users/<?=$user->id?>/edit">Add</a>