<?php
    $users = $viewParams['users'];
?>

<? if (isset($viewParams['deletedUserID']) && $viewParams['deletedUserID']): ?>
    <h2>User with ID <?= $viewParams['deletedUserID'] ?> has been deleted!</h2>
<? endif ?>

<? if (isset($viewParams['editedUserID']) && $viewParams['editedUserID']): ?>
    <h2>User with ID <?= $viewParams['editedUserID'] ?> was edited!</h2>
<? endif ?>

<? if (isset($viewParams['addedUserID']) && $viewParams['addedUserID']): ?>
    <h2>User with ID <?= $viewParams['addedUserID'] ?> was added!</h2>
<? endif ?>

<table border="3" cellpadding="5">
<? foreach ($users as $user): ?>
    <tr>
        <td><?= $user->id ?></td>
        <td><?= $user->name ?></td>
        <td><?= $user->email ?></td>
        <td><?= $user->password ?></td>
        <td>
            <a href="/users/<?=$user->id?>/edit">Edit</a>
        <td>
            <a href="/users/<?=$user->id?>/delete">Delete</a>
        </td>
    </tr>
<? endforeach ?>
</table>
<br>
<a href="/users/add">Create new user</a>